cmake_minimum_required(VERSION 3.15)
project(NovelTradingSystem)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# include_directories(third_party/fast_cpp_csv_parser)

# TODO add main.cpp once configured
# add_executable(NovelTradingSystem src/DataHandlers/HistoricDataHandler/HistoricCSVDataHandler.cpp)