#pragma once
#include "../Event.h"
#include <chrono>
#include <string>

enum class SignalDirection { LONG, SHORT };

// Represents a trading signal generated by a strategy
class SignalEvent : public Event {
public:
  SignalEvent(std::string ticker,
              std::chrono::system_clock::time_point timestamp,
              SignalDirection direction)
      : ticker_(std::move(ticker)), timestamp_(timestamp),
        direction_(direction) {}

  EventType get_type() const override { return EventType::Signal; }

private:
  const std::string ticker_;
  const std::chrono::system_clock::time_point timestamp_;
  const SignalDirection direction_;
};