#pragma once
#include "Events/Bar/BarEvent.h"
#include <chrono>
#include <string>

namespace backtesting_engine::bar {
enum class SignalDirection { LONG, SHORT };

// Overload the << operator
inline std::ostream &operator<<(std::ostream &os, SignalDirection sd) {
  switch (sd) {
  case SignalDirection::LONG:
    return os << "LONG";
  case SignalDirection::SHORT:
    return os << "SHORT";
  default:
    return os << "Unknown";
  }
}

// Represents a trading signal generated by a strategy
class SignalEvent : public Event {
public:
  SignalEvent(std::string ticker,
              std::chrono::system_clock::time_point timestamp,
              SignalDirection direction)
      : ticker_(std::move(ticker)), timestamp_(timestamp),
        direction_(direction) {}

  EventType get_type() const override { return EventType::Signal; }

  const std::string ticker_;
  const std::chrono::system_clock::time_point timestamp_;
  const SignalDirection direction_;
};
} // namespace backtesting_engine::bar
