add_subdirectory(ThreadSafeQueue)
add_subdirectory(Events)
add_subdirectory(ExecutionHandlers)
add_subdirectory(RiskManager)
add_subdirectory(DataHandlers) 
add_subdirectory(Strategies)
add_subdirectory(Portfolio)
add_subdirectory(Statistics)
add_subdirectory(SharedMemory)
add_subdirectory(DataProducers)

add_subdirectory(Constants)
